-- MySQL Script generated by MySQL Workbench
-- seg 07 set 2020 18:29:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Spotfyclone
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Spotfyclone` ;

-- -----------------------------------------------------
-- Schema Spotfyclone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Spotfyclone` ;
USE `Spotfyclone` ;

-- -----------------------------------------------------
-- Table `Spotfyclone`.`planos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotfyclone`.`planos` ;

CREATE TABLE IF NOT EXISTS `Spotfyclone`.`planos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_plano` VARCHAR(55) NOT NULL,
  `valor_plano` DECIMAL(10,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotfyclone`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotfyclone`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `Spotfyclone`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(55) NOT NULL,
  `idade` INT NOT NULL,
  `planos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_planos_idx` (`planos_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_planos`
    FOREIGN KEY (`planos_id`)
    REFERENCES `Spotfyclone`.`planos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotfyclone`.`artistas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotfyclone`.`artistas` ;

CREATE TABLE IF NOT EXISTS `Spotfyclone`.`artistas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_artista` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotfyclone`.`albuns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotfyclone`.`albuns` ;

CREATE TABLE IF NOT EXISTS `Spotfyclone`.`albuns` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_album` VARCHAR(45) NOT NULL,
  `artistas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_albuns_artistas1_idx` (`artistas_id` ASC) VISIBLE,
  CONSTRAINT `fk_albuns_artistas1`
    FOREIGN KEY (`artistas_id`)
    REFERENCES `Spotfyclone`.`artistas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotfyclone`.`cancoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotfyclone`.`cancoes` ;

CREATE TABLE IF NOT EXISTS `Spotfyclone`.`cancoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_musica` VARCHAR(55) NOT NULL,
  `albuns_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cancoes_albuns1_idx` (`albuns_id` ASC) VISIBLE,
  CONSTRAINT `fk_cancoes_albuns1`
    FOREIGN KEY (`albuns_id`)
    REFERENCES `Spotfyclone`.`albuns` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotfyclone`.`seguindo_artistas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotfyclone`.`seguindo_artistas` ;

CREATE TABLE IF NOT EXISTS `Spotfyclone`.`seguindo_artistas` (
  `artistas_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`artistas_id`, `usuarios_id`),
  INDEX `fk_artistas_has_usuarios_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_artistas_has_usuarios_artistas1_idx` (`artistas_id` ASC) VISIBLE,
  CONSTRAINT `fk_artistas_has_usuarios_artistas1`
    FOREIGN KEY (`artistas_id`)
    REFERENCES `Spotfyclone`.`artistas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artistas_has_usuarios_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `Spotfyclone`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotfyclone`.`historico_reproducao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotfyclone`.`historico_reproducao` ;

CREATE TABLE IF NOT EXISTS `Spotfyclone`.`historico_reproducao` (
  `cancoes_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`cancoes_id`, `usuarios_id`),
  INDEX `fk_cancoes_has_usuarios_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_cancoes_has_usuarios_cancoes1_idx` (`cancoes_id` ASC) VISIBLE,
  CONSTRAINT `fk_cancoes_has_usuarios_cancoes1`
    FOREIGN KEY (`cancoes_id`)
    REFERENCES `Spotfyclone`.`cancoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cancoes_has_usuarios_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `Spotfyclone`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
